table ad_spend
	lineageTag: 26b8f74a-5eb8-4d1d-89c9-145e6f40289d

	measure 'Total Spend' = SUM(ad_spend[spend])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 157ad179-fae9-4605-8dd5-83f9ef74512d

	measure 'Attributed Revenue' = SUM(ad_spend[attributed_revenue])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 26d10bfc-cf84-417d-b6ba-614bdd2311e3

	measure ROAS = DIVIDE([Attributed Revenue], [Total Spend])
		formatString: 0.00
		lineageTag: b9feeb09-ddfc-46f6-a2bc-1f2979751d8b

	measure 'Breakeven ROAS' = 1 / [Gross Margin %]
		formatString: 0.00
		lineageTag: f713911a-8ed8-4f26-b6a0-fdb5433051dc

	measure 'Spend Below Breakeven' = SUMX(VALUES(ad_spend[campaign]), IF(CALCULATE([ROAS]) < [Breakeven ROAS], CALCULATE([Total Spend]), 0))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ab080dbb-4260-4198-99c8-d2333e707cdd

	measure '% Spend Below Breakeven' = DIVIDE([Spend Below Breakeven], [Total Spend])
		formatString: 0.0%
		lineageTag: e7507f19-3857-4c2a-9bcd-08373e192a5f

	measure 'ROAS Status Color' = IF([ROAS] < [Breakeven ROAS], "#7F1D1D")
		lineageTag: f72761e1-9099-498d-9e2c-48d0213df56c

	column spend_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d8a4a162-cd81-4979-8a6d-b861deae4e65
		summarizeBy: none
		sourceColumn: spend_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column channel
		dataType: string
		lineageTag: 03342812-424b-4036-a713-7c817345e81e
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column campaign
		dataType: string
		lineageTag: 50df68c5-2a38-4859-8f26-a846b08723a9
		summarizeBy: none
		sourceColumn: campaign

		annotation SummarizationSetBy = Automatic

	column spend
		dataType: double
		lineageTag: 60d3a2a9-8c39-4150-aa4d-0529b027fb39
		summarizeBy: sum
		sourceColumn: spend

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column attributed_revenue
		dataType: double
		lineageTag: cf8dfef0-22a7-4913-b736-a8b36662c8d7
		summarizeBy: sum
		sourceColumn: attributed_revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition ad_spend = m
		mode: import
		source =
				let
				  dataDir = "C:\Users\camry\OneDrive\Desktop\powerbi-n8n\powerbi\data\",
				  load = (file as text, types as list) =>
				    Table.TransformColumnTypes(
				      Table.PromoteHeaders(
				        Csv.Document(File.Contents(dataDir & file), [Delimiter = ",", Encoding = 65001]),
				        [PromoteAllScalars = true]),
				      types),
				  out = [
				    raw_orders = load("raw_orders.csv", {{"order_id", type text}, {"order_date", type date}, {"channel", type text}, {"customer_id", type text}}),
				    raw_order_lines = load("raw_order_lines.csv", {{"order_id", type text}, {"product_id", type text}, {"qty", Int64.Type}, {"line_total", type number}}),
				    raw_products = load("raw_products.csv", {{"product_id", type text}, {"product_name", type text}, {"brand", type text}, {"unit_cost", type number}, {"unit_price", type number}}),
				    ad_spend = load("ad_spend.csv", {{"spend_date", type date}, {"channel", type text}, {"campaign", type text}, {"spend", type number}, {"attributed_revenue", type number}}),
				    inventory_levels = load("inventory_levels.csv", {{"product_id", type text}, {"location", type text}, {"available", Int64.Type}, {"committed", Int64.Type}, {"incoming", Int64.Type}, {"reorder_point", Int64.Type}}),
				    creators = load("creators.csv", {{"creator_id", type text}, {"handle", type text}, {"name", type text}, {"follower_count", Int64.Type}, {"joined_date", type date}}),
				    creator_attributions = load("creator_attributions.csv", {{"order_id", type text}, {"creator_id", type text}, {"attributed_gmv", type number}, {"commission_rate", type number}, {"commission_usd", type number}, {"refunded", type logical}}),
				    search_terms = load("search_terms.csv", {{"month", type date}, {"channel", type text}, {"campaign", type text}, {"search_term", type text}, {"impressions", Int64.Type}, {"clicks", Int64.Type}, {"spend", type number}, {"attributed_revenue", type number}, {"orders", Int64.Type}}),
				    daily_traffic = load("daily_traffic.csv", {{"date", type date}, {"channel", type text}, {"sessions", Int64.Type}, {"product_views", Int64.Type}, {"add_to_carts", Int64.Type}, {"checkouts", Int64.Type}, {"orders", Int64.Type}}),
				    payments = load("payments.csv", {{"order_id", type text}, {"gateway", type text}, {"gross", type number}, {"processing_fee", type number}, {"platform_fee", type number}, {"net_payout", type number}, {"payout_date", type date}}),
				    ar_invoices = load("ar_invoices.csv", {{"invoice_id", type text}, {"order_id", type text}, {"customer_id", type text}, {"invoice_date", type date}, {"terms", type text}, {"due_date", type date}, {"amount", type number}, {"paid_date", type date}})
				  ],
				    ad_spend1 = out[ad_spend]
				in
				  ad_spend1

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

