table ar_invoices
	lineageTag: 2bfa25ca-2dfc-4db7-bcfb-a37773aa2ee1

	measure 'Invoiced A/R' = SUM(ar_invoices[amount])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: da623e9d-46e0-48ef-8fe9-7cf81f6041ab

	measure 'Open A/R' = CALCULATE(SUM(ar_invoices[amount]), ISBLANK(ar_invoices[paid_date]))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6a98d7c7-f25a-43e6-974d-829e05aa08dc

	measure 'Overdue Alert Color' = SWITCH(SELECTEDVALUE(ar_invoices[aging_bucket]), "60+ overdue", "#7F1D1D", "31-60 overdue", "#7A561A", BLANK())
		lineageTag: 987330d4-cf1b-4769-bbe5-baee9872e962

	column invoice_id
		dataType: string
		lineageTag: 3387187a-8946-4341-a18a-cc5989815498
		summarizeBy: none
		sourceColumn: invoice_id

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		lineageTag: 0aaf2c6b-00a1-4ef6-9ea4-c5580d308c7b
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: 43af8a40-75a9-4e11-a3bf-f9ee872e6cd6
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column invoice_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 82f40084-4e29-46f7-a817-0089b7f0c206
		summarizeBy: none
		sourceColumn: invoice_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column terms
		dataType: string
		lineageTag: 7dbcc9a2-36ae-4816-ab4e-76e6e1cd4803
		summarizeBy: none
		sourceColumn: terms

		annotation SummarizationSetBy = Automatic

	column due_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a1143823-434e-4f3b-933d-61b6c8e3565e
		summarizeBy: none
		sourceColumn: due_date

		variation Variation
			isDefault
			relationship: ba8e65e9-4f1d-4dbb-8124-ca94843e5f9a
			defaultHierarchy: LocalDateTable_c3d1c8f1-2107-40f3-97a2-efa4b010d011.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column amount
		dataType: double
		lineageTag: 8690e78d-e223-4247-a3ae-52e28b9b0607
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column paid_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: f1707cae-824f-49e1-81f4-33881d75c902
		summarizeBy: none
		sourceColumn: paid_date

		variation Variation
			isDefault
			relationship: 8f071f5d-b0fc-4d91-970f-5e547a0fb181
			defaultHierarchy: LocalDateTable_eb23658c-2bae-4099-ac3d-c0a1c3e85f32.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column aging_bucket = VAR days = INT(DATE(2026, 7, 25) - ar_invoices[due_date]) RETURN IF(NOT ISBLANK(ar_invoices[paid_date]), "Paid", IF(days < 0, "Current", IF(days <= 30, "1-30 overdue", IF(days <= 60, "31-60 overdue", "60+ overdue"))))
		dataType: string
		lineageTag: ef984963-cca8-4750-aa07-6db804cc8819
		summarizeBy: none

	partition ar_invoices = m
		mode: import
		source =
				let
				  dataDir = "C:\Users\camry\OneDrive\Desktop\powerbi-n8n\powerbi\data\",
				  load = (file as text, types as list) =>
				    Table.TransformColumnTypes(
				      Table.PromoteHeaders(
				        Csv.Document(File.Contents(dataDir & file), [Delimiter = ",", Encoding = 65001]),
				        [PromoteAllScalars = true]),
				      types),
				  out = [
				    raw_orders = load("raw_orders.csv", {{"order_id", type text}, {"order_date", type date}, {"channel", type text}, {"customer_id", type text}}),
				    raw_order_lines = load("raw_order_lines.csv", {{"order_id", type text}, {"product_id", type text}, {"qty", Int64.Type}, {"line_total", type number}}),
				    raw_products = load("raw_products.csv", {{"product_id", type text}, {"product_name", type text}, {"brand", type text}, {"unit_cost", type number}, {"unit_price", type number}}),
				    ad_spend = load("ad_spend.csv", {{"spend_date", type date}, {"channel", type text}, {"campaign", type text}, {"spend", type number}, {"attributed_revenue", type number}}),
				    inventory_levels = load("inventory_levels.csv", {{"product_id", type text}, {"location", type text}, {"available", Int64.Type}, {"committed", Int64.Type}, {"incoming", Int64.Type}, {"reorder_point", Int64.Type}}),
				    creators = load("creators.csv", {{"creator_id", type text}, {"handle", type text}, {"name", type text}, {"follower_count", Int64.Type}, {"joined_date", type date}}),
				    creator_attributions = load("creator_attributions.csv", {{"order_id", type text}, {"creator_id", type text}, {"attributed_gmv", type number}, {"commission_rate", type number}, {"commission_usd", type number}, {"refunded", type logical}}),
				    search_terms = load("search_terms.csv", {{"month", type date}, {"channel", type text}, {"campaign", type text}, {"search_term", type text}, {"impressions", Int64.Type}, {"clicks", Int64.Type}, {"spend", type number}, {"attributed_revenue", type number}, {"orders", Int64.Type}}),
				    daily_traffic = load("daily_traffic.csv", {{"date", type date}, {"channel", type text}, {"sessions", Int64.Type}, {"product_views", Int64.Type}, {"add_to_carts", Int64.Type}, {"checkouts", Int64.Type}, {"orders", Int64.Type}}),
				    payments = load("payments.csv", {{"order_id", type text}, {"gateway", type text}, {"gross", type number}, {"processing_fee", type number}, {"platform_fee", type number}, {"net_payout", type number}, {"payout_date", type date}}),
				    ar_invoices = load("ar_invoices.csv", {{"invoice_id", type text}, {"order_id", type text}, {"customer_id", type text}, {"invoice_date", type date}, {"terms", type text}, {"due_date", type date}, {"amount", type number}, {"paid_date", type date}})
				  ],
				    ar_invoices1 = out[ar_invoices]
				in
				  ar_invoices1

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

