table creators
	lineageTag: e9f486c0-817e-48ad-a879-0aa53bfe1fc2

	column creator_id
		dataType: string
		lineageTag: d5cd3ced-a518-4ace-a73f-a345e380d679
		summarizeBy: none
		sourceColumn: creator_id

		annotation SummarizationSetBy = Automatic

	column handle
		dataType: string
		lineageTag: f7c53dd9-7981-4d58-b258-a817b36fc56a
		summarizeBy: none
		sourceColumn: handle

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: a9757e8a-215b-4610-ae96-9052a9a5f346
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column follower_count
		dataType: int64
		formatString: 0
		lineageTag: fbc2c5ad-6e74-4b0a-baa6-73a161cc57e5
		summarizeBy: sum
		sourceColumn: follower_count

		annotation SummarizationSetBy = Automatic

	column joined_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d10f3cc0-5150-4827-a89d-be6c11e3ee32
		summarizeBy: none
		sourceColumn: joined_date

		variation Variation
			isDefault
			relationship: 8a2d00f2-21c8-4c35-a29e-1c8e8e66b578
			defaultHierarchy: LocalDateTable_8a27ba49-9d6b-4d7d-a997-289a8fe17abc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition creators = m
		mode: import
		source =
				let
				  dataDir = "C:\Users\camry\OneDrive\Desktop\powerbi-n8n\powerbi\data\",
				  load = (file as text, types as list) =>
				    Table.TransformColumnTypes(
				      Table.PromoteHeaders(
				        Csv.Document(File.Contents(dataDir & file), [Delimiter = ",", Encoding = 65001]),
				        [PromoteAllScalars = true]),
				      types),
				  out = [
				    raw_orders = load("raw_orders.csv", {{"order_id", type text}, {"order_date", type date}, {"channel", type text}, {"customer_id", type text}}),
				    raw_order_lines = load("raw_order_lines.csv", {{"order_id", type text}, {"product_id", type text}, {"qty", Int64.Type}, {"line_total", type number}}),
				    raw_products = load("raw_products.csv", {{"product_id", type text}, {"product_name", type text}, {"brand", type text}, {"unit_cost", type number}, {"unit_price", type number}}),
				    ad_spend = load("ad_spend.csv", {{"spend_date", type date}, {"channel", type text}, {"campaign", type text}, {"spend", type number}, {"attributed_revenue", type number}}),
				    inventory_levels = load("inventory_levels.csv", {{"product_id", type text}, {"location", type text}, {"available", Int64.Type}, {"committed", Int64.Type}, {"incoming", Int64.Type}, {"reorder_point", Int64.Type}}),
				    creators = load("creators.csv", {{"creator_id", type text}, {"handle", type text}, {"name", type text}, {"follower_count", Int64.Type}, {"joined_date", type date}}),
				    creator_attributions = load("creator_attributions.csv", {{"order_id", type text}, {"creator_id", type text}, {"attributed_gmv", type number}, {"commission_rate", type number}, {"commission_usd", type number}, {"refunded", type logical}}),
				    search_terms = load("search_terms.csv", {{"month", type date}, {"channel", type text}, {"campaign", type text}, {"search_term", type text}, {"impressions", Int64.Type}, {"clicks", Int64.Type}, {"spend", type number}, {"attributed_revenue", type number}, {"orders", Int64.Type}}),
				    daily_traffic = load("daily_traffic.csv", {{"date", type date}, {"channel", type text}, {"sessions", Int64.Type}, {"product_views", Int64.Type}, {"add_to_carts", Int64.Type}, {"checkouts", Int64.Type}, {"orders", Int64.Type}}),
				    payments = load("payments.csv", {{"order_id", type text}, {"gateway", type text}, {"gross", type number}, {"processing_fee", type number}, {"platform_fee", type number}, {"net_payout", type number}, {"payout_date", type date}}),
				    ar_invoices = load("ar_invoices.csv", {{"invoice_id", type text}, {"order_id", type text}, {"customer_id", type text}, {"invoice_date", type date}, {"terms", type text}, {"due_date", type date}, {"amount", type number}, {"paid_date", type date}})
				  ],
				    creators1 = out[creators]
				in
				  creators1

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

