table creator_attributions
	lineageTag: 6f505d98-6d3a-4202-b833-6cd3221caa41

	measure 'Creator GMV' = CALCULATE(SUM(creator_attributions[attributed_gmv]), creator_attributions[refunded] = FALSE())
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d1711ba6-44d9-455b-adbc-baf70dfd3f8b

	measure 'Refund GMV' = CALCULATE(SUM(creator_attributions[attributed_gmv]), creator_attributions[refunded] = TRUE())
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: cb030ec1-355a-4970-a429-7282513a4a16

	measure 'Refund Rate' = DIVIDE([Refund GMV], [Refund GMV] + [Creator GMV])
		formatString: 0.0%
		lineageTag: 1d353d48-948f-495a-a6af-3c1893731fe3

	measure 'Commission Paid' = SUM(creator_attributions[commission_usd])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 866a8151-0293-4a3c-a493-9283d5920866

	measure 'GMV per Follower' = DIVIDE([Creator GMV], SUM(creators[follower_count]))
		formatString: 0.0000
		lineageTag: 09faef19-ae89-44b9-966b-c0cb5f022a12

	measure 'Last Attributed Order' = CALCULATE(MAX(raw_orders[order_date]), CROSSFILTER(creator_attributions[order_id], raw_orders[order_id], BOTH))
		lineageTag: 7e8ffe8e-e1b8-45ed-86c2-91ce5e7dec9c

	measure 'Days Since Last Order' = DATEDIFF([Last Attributed Order], [Data As-Of], DAY)
		formatString: #,0
		lineageTag: 7aed7404-91e2-4619-8ebe-6c801ea4cc97

	measure 'Refund Alert Color' = IF([Refund Rate] > 0.15, "#7F1D1D", BLANK())
		lineageTag: ca964c17-ca83-435f-897e-5cc1b378fbc9

	measure 'Decay Alert Color' = IF([Days Since Last Order] > 30, "#7A561A", BLANK())
		lineageTag: 85ce1f6c-0aa7-45a4-8c5b-76c2a79cf4d9

	column order_id
		dataType: string
		lineageTag: 6c0b43ce-33e2-4079-b223-b192e14ee001
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column creator_id
		dataType: string
		lineageTag: b15d4174-b787-4d12-93ff-2c90e118dc5e
		summarizeBy: none
		sourceColumn: creator_id

		annotation SummarizationSetBy = Automatic

	column attributed_gmv
		dataType: double
		lineageTag: 95d58116-45e5-4f49-8514-4a2b98e953aa
		summarizeBy: sum
		sourceColumn: attributed_gmv

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column commission_rate
		dataType: double
		lineageTag: f833df4b-0cd6-4931-bc3b-b8fc37960f66
		summarizeBy: sum
		sourceColumn: commission_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column commission_usd
		dataType: double
		lineageTag: 8e4f56e4-afd0-41b1-abb6-c6f894f8dae7
		summarizeBy: sum
		sourceColumn: commission_usd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column refunded
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1be9c5fd-02ba-4b2f-969f-70cd4a668a2e
		summarizeBy: none
		sourceColumn: refunded

		annotation SummarizationSetBy = Automatic

	partition creator_attributions = m
		mode: import
		source =
				let
				  dataDir = "C:\Users\camry\OneDrive\Desktop\powerbi-n8n\powerbi\data\",
				  load = (file as text, types as list) =>
				    Table.TransformColumnTypes(
				      Table.PromoteHeaders(
				        Csv.Document(File.Contents(dataDir & file), [Delimiter = ",", Encoding = 65001]),
				        [PromoteAllScalars = true]),
				      types),
				  out = [
				    raw_orders = load("raw_orders.csv", {{"order_id", type text}, {"order_date", type date}, {"channel", type text}, {"customer_id", type text}}),
				    raw_order_lines = load("raw_order_lines.csv", {{"order_id", type text}, {"product_id", type text}, {"qty", Int64.Type}, {"line_total", type number}}),
				    raw_products = load("raw_products.csv", {{"product_id", type text}, {"product_name", type text}, {"brand", type text}, {"unit_cost", type number}, {"unit_price", type number}}),
				    ad_spend = load("ad_spend.csv", {{"spend_date", type date}, {"channel", type text}, {"campaign", type text}, {"spend", type number}, {"attributed_revenue", type number}}),
				    inventory_levels = load("inventory_levels.csv", {{"product_id", type text}, {"location", type text}, {"available", Int64.Type}, {"committed", Int64.Type}, {"incoming", Int64.Type}, {"reorder_point", Int64.Type}}),
				    creators = load("creators.csv", {{"creator_id", type text}, {"handle", type text}, {"name", type text}, {"follower_count", Int64.Type}, {"joined_date", type date}}),
				    creator_attributions = load("creator_attributions.csv", {{"order_id", type text}, {"creator_id", type text}, {"attributed_gmv", type number}, {"commission_rate", type number}, {"commission_usd", type number}, {"refunded", type logical}}),
				    search_terms = load("search_terms.csv", {{"month", type date}, {"channel", type text}, {"campaign", type text}, {"search_term", type text}, {"impressions", Int64.Type}, {"clicks", Int64.Type}, {"spend", type number}, {"attributed_revenue", type number}, {"orders", Int64.Type}}),
				    daily_traffic = load("daily_traffic.csv", {{"date", type date}, {"channel", type text}, {"sessions", Int64.Type}, {"product_views", Int64.Type}, {"add_to_carts", Int64.Type}, {"checkouts", Int64.Type}, {"orders", Int64.Type}}),
				    payments = load("payments.csv", {{"order_id", type text}, {"gateway", type text}, {"gross", type number}, {"processing_fee", type number}, {"platform_fee", type number}, {"net_payout", type number}, {"payout_date", type date}}),
				    ar_invoices = load("ar_invoices.csv", {{"invoice_id", type text}, {"order_id", type text}, {"customer_id", type text}, {"invoice_date", type date}, {"terms", type text}, {"due_date", type date}, {"amount", type number}, {"paid_date", type date}})
				  ],
				    creator_attributions1 = out[creator_attributions]
				in
				  creator_attributions1

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

