table daily_traffic
	lineageTag: 03f1d77e-93cc-475a-8c2a-972728989289

	measure 'Total Sessions' = SUM(daily_traffic[sessions])
		formatString: #,0
		lineageTag: be39d4d8-6292-4c65-9694-454c36126bcf

	measure 'Session CVR' = DIVIDE(SUM(daily_traffic[orders]), [Total Sessions])
		formatString: 0.00%
		lineageTag: ca9542a3-e20d-4630-8943-6f4d3648ecea

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a114defe-ed86-4790-b329-c5ee14726b0e
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column channel
		dataType: string
		lineageTag: 9b282026-0bf2-448d-80de-123d7c915cd9
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column sessions
		dataType: int64
		formatString: 0
		lineageTag: 7b6bb352-7833-46a7-8a09-59c64304a89a
		summarizeBy: sum
		sourceColumn: sessions

		annotation SummarizationSetBy = Automatic

	column product_views
		dataType: int64
		formatString: 0
		lineageTag: 1ec747be-35a2-4868-86f0-db3ae3b62a30
		summarizeBy: sum
		sourceColumn: product_views

		annotation SummarizationSetBy = Automatic

	column add_to_carts
		dataType: int64
		formatString: 0
		lineageTag: 3267b94e-018d-4759-8a0e-bd930da6e789
		summarizeBy: sum
		sourceColumn: add_to_carts

		annotation SummarizationSetBy = Automatic

	column checkouts
		dataType: int64
		formatString: 0
		lineageTag: 9a15c719-d831-4cd6-a8ce-b3a33182e662
		summarizeBy: sum
		sourceColumn: checkouts

		annotation SummarizationSetBy = Automatic

	column orders
		dataType: int64
		formatString: 0
		lineageTag: a7a245a2-c544-4692-aa73-1af1cc05a9ce
		summarizeBy: sum
		sourceColumn: orders

		annotation SummarizationSetBy = Automatic

	partition daily_traffic = m
		mode: import
		source =
				let
				  dataDir = "C:\Users\camry\OneDrive\Desktop\powerbi-n8n\powerbi\data\",
				  load = (file as text, types as list) =>
				    Table.TransformColumnTypes(
				      Table.PromoteHeaders(
				        Csv.Document(File.Contents(dataDir & file), [Delimiter = ",", Encoding = 65001]),
				        [PromoteAllScalars = true]),
				      types),
				  out = [
				    raw_orders = load("raw_orders.csv", {{"order_id", type text}, {"order_date", type date}, {"channel", type text}, {"customer_id", type text}}),
				    raw_order_lines = load("raw_order_lines.csv", {{"order_id", type text}, {"product_id", type text}, {"qty", Int64.Type}, {"line_total", type number}}),
				    raw_products = load("raw_products.csv", {{"product_id", type text}, {"product_name", type text}, {"brand", type text}, {"unit_cost", type number}, {"unit_price", type number}}),
				    ad_spend = load("ad_spend.csv", {{"spend_date", type date}, {"channel", type text}, {"campaign", type text}, {"spend", type number}, {"attributed_revenue", type number}}),
				    inventory_levels = load("inventory_levels.csv", {{"product_id", type text}, {"location", type text}, {"available", Int64.Type}, {"committed", Int64.Type}, {"incoming", Int64.Type}, {"reorder_point", Int64.Type}}),
				    creators = load("creators.csv", {{"creator_id", type text}, {"handle", type text}, {"name", type text}, {"follower_count", Int64.Type}, {"joined_date", type date}}),
				    creator_attributions = load("creator_attributions.csv", {{"order_id", type text}, {"creator_id", type text}, {"attributed_gmv", type number}, {"commission_rate", type number}, {"commission_usd", type number}, {"refunded", type logical}}),
				    search_terms = load("search_terms.csv", {{"month", type date}, {"channel", type text}, {"campaign", type text}, {"search_term", type text}, {"impressions", Int64.Type}, {"clicks", Int64.Type}, {"spend", type number}, {"attributed_revenue", type number}, {"orders", Int64.Type}}),
				    daily_traffic = load("daily_traffic.csv", {{"date", type date}, {"channel", type text}, {"sessions", Int64.Type}, {"product_views", Int64.Type}, {"add_to_carts", Int64.Type}, {"checkouts", Int64.Type}, {"orders", Int64.Type}}),
				    payments = load("payments.csv", {{"order_id", type text}, {"gateway", type text}, {"gross", type number}, {"processing_fee", type number}, {"platform_fee", type number}, {"net_payout", type number}, {"payout_date", type date}}),
				    ar_invoices = load("ar_invoices.csv", {{"invoice_id", type text}, {"order_id", type text}, {"customer_id", type text}, {"invoice_date", type date}, {"terms", type text}, {"due_date", type date}, {"amount", type number}, {"paid_date", type date}})
				  ],
				    daily_traffic1 = out[daily_traffic]
				in
				  daily_traffic1

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

