table inventory_levels
	lineageTag: 9b519ac4-fd87-40e9-bf4a-f106106f5233

	measure 'Available Units' = SUM(inventory_levels[available])
		formatString: #,0
		lineageTag: 877e4a62-561e-4bb7-a043-3b4b971fa613

	measure 'Stockout Locations' = COUNTROWS(FILTER(inventory_levels, inventory_levels[available] = 0))
		formatString: #,0
		lineageTag: 02c817a8-c76d-4205-a8bf-44744e18159a

	measure 'Low Stock Locations' = COUNTROWS(FILTER(inventory_levels, inventory_levels[available] > 0 && inventory_levels[available] <= 10))
		formatString: #,0
		lineageTag: b5f816cb-f10c-44aa-baf9-f68c920ed9aa

	measure 'Units Sold 90d' = CALCULATE(SUM(raw_order_lines[qty]), DATESINPERIOD(DateDim[Date], [Data As-Of], -90, DAY), ALL(DateDim))
		formatString: #,0
		lineageTag: 00a807a8-d52b-4d88-8b1a-8dc4e5e4469b

	measure 'Days of Cover' = DIVIDE([Available Units], DIVIDE([Units Sold 90d], 90))
		formatString: 0.0
		lineageTag: 40a35ddf-e060-4ba8-a457-07603e19a40e

	measure 'Cover Alert Color' = IF([Days of Cover] < 14, "#7F1D1D", IF([Days of Cover] < 30, "#7A561A", BLANK()))
		lineageTag: 3d629e69-c557-44d2-8c7d-7e3ddc717761

	column product_id
		dataType: string
		lineageTag: 77c78593-edc9-4b05-9b3d-9ada6a50e6c7
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 672d25e5-a835-46cc-95c6-65dce038e6e8
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column available
		dataType: int64
		formatString: 0
		lineageTag: 46570053-8dc2-429b-8659-70b5cdfdf427
		summarizeBy: sum
		sourceColumn: available

		annotation SummarizationSetBy = Automatic

	column committed
		dataType: int64
		formatString: 0
		lineageTag: ab797b8d-7d4a-4b6f-bf42-e0e89e3dd3ea
		summarizeBy: sum
		sourceColumn: committed

		annotation SummarizationSetBy = Automatic

	column incoming
		dataType: int64
		formatString: 0
		lineageTag: cde75625-5308-4409-ae66-dbb2e9412a26
		summarizeBy: sum
		sourceColumn: incoming

		annotation SummarizationSetBy = Automatic

	column reorder_point
		dataType: int64
		formatString: 0
		lineageTag: 0786d2b8-eb71-44ff-a8df-eefffe99527d
		summarizeBy: sum
		sourceColumn: reorder_point

		annotation SummarizationSetBy = Automatic

	partition inventory_levels = m
		mode: import
		source =
				let
				  dataDir = "C:\Users\camry\OneDrive\Desktop\powerbi-n8n\powerbi\data\",
				  load = (file as text, types as list) =>
				    Table.TransformColumnTypes(
				      Table.PromoteHeaders(
				        Csv.Document(File.Contents(dataDir & file), [Delimiter = ",", Encoding = 65001]),
				        [PromoteAllScalars = true]),
				      types),
				  out = [
				    raw_orders = load("raw_orders.csv", {{"order_id", type text}, {"order_date", type date}, {"channel", type text}, {"customer_id", type text}}),
				    raw_order_lines = load("raw_order_lines.csv", {{"order_id", type text}, {"product_id", type text}, {"qty", Int64.Type}, {"line_total", type number}}),
				    raw_products = load("raw_products.csv", {{"product_id", type text}, {"product_name", type text}, {"brand", type text}, {"unit_cost", type number}, {"unit_price", type number}}),
				    ad_spend = load("ad_spend.csv", {{"spend_date", type date}, {"channel", type text}, {"campaign", type text}, {"spend", type number}, {"attributed_revenue", type number}}),
				    inventory_levels = load("inventory_levels.csv", {{"product_id", type text}, {"location", type text}, {"available", Int64.Type}, {"committed", Int64.Type}, {"incoming", Int64.Type}, {"reorder_point", Int64.Type}}),
				    creators = load("creators.csv", {{"creator_id", type text}, {"handle", type text}, {"name", type text}, {"follower_count", Int64.Type}, {"joined_date", type date}}),
				    creator_attributions = load("creator_attributions.csv", {{"order_id", type text}, {"creator_id", type text}, {"attributed_gmv", type number}, {"commission_rate", type number}, {"commission_usd", type number}, {"refunded", type logical}}),
				    search_terms = load("search_terms.csv", {{"month", type date}, {"channel", type text}, {"campaign", type text}, {"search_term", type text}, {"impressions", Int64.Type}, {"clicks", Int64.Type}, {"spend", type number}, {"attributed_revenue", type number}, {"orders", Int64.Type}}),
				    daily_traffic = load("daily_traffic.csv", {{"date", type date}, {"channel", type text}, {"sessions", Int64.Type}, {"product_views", Int64.Type}, {"add_to_carts", Int64.Type}, {"checkouts", Int64.Type}, {"orders", Int64.Type}}),
				    payments = load("payments.csv", {{"order_id", type text}, {"gateway", type text}, {"gross", type number}, {"processing_fee", type number}, {"platform_fee", type number}, {"net_payout", type number}, {"payout_date", type date}}),
				    ar_invoices = load("ar_invoices.csv", {{"invoice_id", type text}, {"order_id", type text}, {"customer_id", type text}, {"invoice_date", type date}, {"terms", type text}, {"due_date", type date}, {"amount", type number}, {"paid_date", type date}})
				  ],
				    inventory_levels1 = out[inventory_levels]
				in
				  inventory_levels1

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

