table payments
	lineageTag: ec4bd9ef-113a-490b-8747-5cbc08d614d7

	measure 'Gross Payments' = SUM(payments[gross])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 5d045d15-b14f-4d4c-bf56-90b577360469

	measure 'Total Fees' = SUM(payments[processing_fee]) + SUM(payments[platform_fee])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 06c9ba4f-8c4e-4880-94c2-c1fa3d065320

	measure 'Net Payout' = SUM(payments[net_payout])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 2c1a2973-9a2e-4d86-ad5f-606ad20532f3

	measure 'Take Rate %' = DIVIDE([Total Fees], [Gross Payments])
		formatString: 0.0%
		lineageTag: 08dda03d-bbeb-4312-af29-d40cf429178a

	column order_id
		dataType: string
		lineageTag: fce3c39a-a3aa-4e56-b758-49a62ca8cb2b
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column gateway
		dataType: string
		lineageTag: 64c5854f-bd19-4481-8659-7c17ce3bf158
		summarizeBy: none
		sourceColumn: gateway

		annotation SummarizationSetBy = Automatic

	column gross
		dataType: double
		lineageTag: 40699431-af1b-419f-9a2e-82f723fd4cf6
		summarizeBy: sum
		sourceColumn: gross

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column processing_fee
		dataType: double
		lineageTag: 3546a2a4-08f0-44c0-add2-062b5510fb89
		summarizeBy: sum
		sourceColumn: processing_fee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column platform_fee
		dataType: double
		lineageTag: 7a1d86e2-79c3-44b4-b44f-9de528a42ec9
		summarizeBy: sum
		sourceColumn: platform_fee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column net_payout
		dataType: double
		lineageTag: 6d6822a1-3ee9-4a6d-91ca-f42a874068a9
		summarizeBy: sum
		sourceColumn: net_payout

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column payout_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 042b42fe-bf64-4440-87a3-29f6286e6719
		summarizeBy: none
		sourceColumn: payout_date

		variation Variation
			isDefault
			relationship: a2c645c9-f551-4d58-ad77-87328e8d600c
			defaultHierarchy: LocalDateTable_f712960c-a29b-459d-b40a-5d24e6065d59.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition payments = m
		mode: import
		source =
				let
				  dataDir = "C:\Users\camry\OneDrive\Desktop\powerbi-n8n\powerbi\data\",
				  load = (file as text, types as list) =>
				    Table.TransformColumnTypes(
				      Table.PromoteHeaders(
				        Csv.Document(File.Contents(dataDir & file), [Delimiter = ",", Encoding = 65001]),
				        [PromoteAllScalars = true]),
				      types),
				  out = [
				    raw_orders = load("raw_orders.csv", {{"order_id", type text}, {"order_date", type date}, {"channel", type text}, {"customer_id", type text}}),
				    raw_order_lines = load("raw_order_lines.csv", {{"order_id", type text}, {"product_id", type text}, {"qty", Int64.Type}, {"line_total", type number}}),
				    raw_products = load("raw_products.csv", {{"product_id", type text}, {"product_name", type text}, {"brand", type text}, {"unit_cost", type number}, {"unit_price", type number}}),
				    ad_spend = load("ad_spend.csv", {{"spend_date", type date}, {"channel", type text}, {"campaign", type text}, {"spend", type number}, {"attributed_revenue", type number}}),
				    inventory_levels = load("inventory_levels.csv", {{"product_id", type text}, {"location", type text}, {"available", Int64.Type}, {"committed", Int64.Type}, {"incoming", Int64.Type}, {"reorder_point", Int64.Type}}),
				    creators = load("creators.csv", {{"creator_id", type text}, {"handle", type text}, {"name", type text}, {"follower_count", Int64.Type}, {"joined_date", type date}}),
				    creator_attributions = load("creator_attributions.csv", {{"order_id", type text}, {"creator_id", type text}, {"attributed_gmv", type number}, {"commission_rate", type number}, {"commission_usd", type number}, {"refunded", type logical}}),
				    search_terms = load("search_terms.csv", {{"month", type date}, {"channel", type text}, {"campaign", type text}, {"search_term", type text}, {"impressions", Int64.Type}, {"clicks", Int64.Type}, {"spend", type number}, {"attributed_revenue", type number}, {"orders", Int64.Type}}),
				    daily_traffic = load("daily_traffic.csv", {{"date", type date}, {"channel", type text}, {"sessions", Int64.Type}, {"product_views", Int64.Type}, {"add_to_carts", Int64.Type}, {"checkouts", Int64.Type}, {"orders", Int64.Type}}),
				    payments = load("payments.csv", {{"order_id", type text}, {"gateway", type text}, {"gross", type number}, {"processing_fee", type number}, {"platform_fee", type number}, {"net_payout", type number}, {"payout_date", type date}}),
				    ar_invoices = load("ar_invoices.csv", {{"invoice_id", type text}, {"order_id", type text}, {"customer_id", type text}, {"invoice_date", type date}, {"terms", type text}, {"due_date", type date}, {"amount", type number}, {"paid_date", type date}})
				  ],
				    payments1 = out[payments]
				in
				  payments1

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

