table raw_order_lines
	lineageTag: e09fe93e-7510-4f02-a45a-4d8dee417139

	measure 'Total Revenue' = SUM(raw_order_lines[line_total])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4cd6a168-98c5-4f7d-9f43-1a4c69d7af3d

	measure Orders = DISTINCTCOUNT(raw_order_lines[order_id])
		formatString: #,0
		lineageTag: d36ca8c1-2c25-4d61-982a-ccd228b487db

	measure AOV = DIVIDE([Total Revenue], [Orders])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 38df6db4-ac7e-483c-8e12-4d93b38c9706

	measure 'Total Cost' = SUMX(raw_order_lines, raw_order_lines[qty] * RELATED(raw_products[unit_cost]))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: adb9574a-3f2d-4fee-9d09-702162dd29fb

	measure 'Gross Margin %' = DIVIDE([Total Revenue] - [Total Cost], [Total Revenue])
		formatString: 0.0%
		lineageTag: 59af04d2-7c36-4aaf-ac6a-0f3b1e170808

	measure 'Revenue MoM %' = VAR prev = CALCULATE([Total Revenue], DATEADD(DateDim[Date], -1, MONTH)) RETURN DIVIDE([Total Revenue] - prev, prev)
		formatString: 0.0%
		lineageTag: eebe9dea-f2da-49b5-a4ef-6e1c81b77297

	measure 'Data As-Of' = CALCULATE(MAX(raw_orders[order_date]), ALL(raw_orders))
		lineageTag: 2974f60d-049d-445e-8870-307a28d35d07

	column order_id
		dataType: string
		lineageTag: fd160e4d-d0b0-46a6-be99-1319185e09b9
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: fe6408b5-7197-409b-981e-0ebf7168c11b
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column qty
		dataType: int64
		formatString: 0
		lineageTag: dd78997e-3c44-4904-8379-4a8b60ce5d21
		summarizeBy: sum
		sourceColumn: qty

		annotation SummarizationSetBy = Automatic

	column line_total
		dataType: double
		lineageTag: 41587ee8-7575-4161-8149-c871664aa2ad
		summarizeBy: sum
		sourceColumn: line_total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition raw_order_lines = m
		mode: import
		source =
				let
				  dataDir = "C:\Users\camry\OneDrive\Desktop\powerbi-n8n\powerbi\data\",
				  load = (file as text, types as list) =>
				    Table.TransformColumnTypes(
				      Table.PromoteHeaders(
				        Csv.Document(File.Contents(dataDir & file), [Delimiter = ",", Encoding = 65001]),
				        [PromoteAllScalars = true]),
				      types),
				  out = [
				    raw_orders = load("raw_orders.csv", {{"order_id", type text}, {"order_date", type date}, {"channel", type text}, {"customer_id", type text}}),
				    raw_order_lines = load("raw_order_lines.csv", {{"order_id", type text}, {"product_id", type text}, {"qty", Int64.Type}, {"line_total", type number}}),
				    raw_products = load("raw_products.csv", {{"product_id", type text}, {"product_name", type text}, {"brand", type text}, {"unit_cost", type number}, {"unit_price", type number}}),
				    ad_spend = load("ad_spend.csv", {{"spend_date", type date}, {"channel", type text}, {"campaign", type text}, {"spend", type number}, {"attributed_revenue", type number}}),
				    inventory_levels = load("inventory_levels.csv", {{"product_id", type text}, {"location", type text}, {"available", Int64.Type}, {"committed", Int64.Type}, {"incoming", Int64.Type}, {"reorder_point", Int64.Type}}),
				    creators = load("creators.csv", {{"creator_id", type text}, {"handle", type text}, {"name", type text}, {"follower_count", Int64.Type}, {"joined_date", type date}}),
				    creator_attributions = load("creator_attributions.csv", {{"order_id", type text}, {"creator_id", type text}, {"attributed_gmv", type number}, {"commission_rate", type number}, {"commission_usd", type number}, {"refunded", type logical}}),
				    search_terms = load("search_terms.csv", {{"month", type date}, {"channel", type text}, {"campaign", type text}, {"search_term", type text}, {"impressions", Int64.Type}, {"clicks", Int64.Type}, {"spend", type number}, {"attributed_revenue", type number}, {"orders", Int64.Type}}),
				    daily_traffic = load("daily_traffic.csv", {{"date", type date}, {"channel", type text}, {"sessions", Int64.Type}, {"product_views", Int64.Type}, {"add_to_carts", Int64.Type}, {"checkouts", Int64.Type}, {"orders", Int64.Type}}),
				    payments = load("payments.csv", {{"order_id", type text}, {"gateway", type text}, {"gross", type number}, {"processing_fee", type number}, {"platform_fee", type number}, {"net_payout", type number}, {"payout_date", type date}}),
				    ar_invoices = load("ar_invoices.csv", {{"invoice_id", type text}, {"order_id", type text}, {"customer_id", type text}, {"invoice_date", type date}, {"terms", type text}, {"due_date", type date}, {"amount", type number}, {"paid_date", type date}})
				  ],
				    raw_order_lines1 = out[raw_order_lines]
				in
				  raw_order_lines1

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

