table raw_products
	lineageTag: cd56b1c0-ea36-4e2f-bdab-e128b8acdcc0

	column product_id
		dataType: string
		lineageTag: 489151f4-91c0-4db2-8c38-aae4dc0a4e07
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: d7d33f41-e0c6-4f9a-80c1-8034bb8cf413
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column brand
		dataType: string
		lineageTag: d00ab940-9397-488e-9e63-7c29044673dd
		summarizeBy: none
		sourceColumn: brand

		annotation SummarizationSetBy = Automatic

	column unit_cost
		dataType: double
		lineageTag: c23f5b44-2928-496d-8453-5c41358b1805
		summarizeBy: sum
		sourceColumn: unit_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column unit_price
		dataType: double
		lineageTag: d0ee880f-33aa-4272-800b-226d56baf4e5
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition raw_products = m
		mode: import
		source =
				let
				  dataDir = "C:\Users\camry\OneDrive\Desktop\powerbi-n8n\powerbi\data\",
				  load = (file as text, types as list) =>
				    Table.TransformColumnTypes(
				      Table.PromoteHeaders(
				        Csv.Document(File.Contents(dataDir & file), [Delimiter = ",", Encoding = 65001]),
				        [PromoteAllScalars = true]),
				      types),
				  out = [
				    raw_orders = load("raw_orders.csv", {{"order_id", type text}, {"order_date", type date}, {"channel", type text}, {"customer_id", type text}}),
				    raw_order_lines = load("raw_order_lines.csv", {{"order_id", type text}, {"product_id", type text}, {"qty", Int64.Type}, {"line_total", type number}}),
				    raw_products = load("raw_products.csv", {{"product_id", type text}, {"product_name", type text}, {"brand", type text}, {"unit_cost", type number}, {"unit_price", type number}}),
				    ad_spend = load("ad_spend.csv", {{"spend_date", type date}, {"channel", type text}, {"campaign", type text}, {"spend", type number}, {"attributed_revenue", type number}}),
				    inventory_levels = load("inventory_levels.csv", {{"product_id", type text}, {"location", type text}, {"available", Int64.Type}, {"committed", Int64.Type}, {"incoming", Int64.Type}, {"reorder_point", Int64.Type}}),
				    creators = load("creators.csv", {{"creator_id", type text}, {"handle", type text}, {"name", type text}, {"follower_count", Int64.Type}, {"joined_date", type date}}),
				    creator_attributions = load("creator_attributions.csv", {{"order_id", type text}, {"creator_id", type text}, {"attributed_gmv", type number}, {"commission_rate", type number}, {"commission_usd", type number}, {"refunded", type logical}}),
				    search_terms = load("search_terms.csv", {{"month", type date}, {"channel", type text}, {"campaign", type text}, {"search_term", type text}, {"impressions", Int64.Type}, {"clicks", Int64.Type}, {"spend", type number}, {"attributed_revenue", type number}, {"orders", Int64.Type}}),
				    daily_traffic = load("daily_traffic.csv", {{"date", type date}, {"channel", type text}, {"sessions", Int64.Type}, {"product_views", Int64.Type}, {"add_to_carts", Int64.Type}, {"checkouts", Int64.Type}, {"orders", Int64.Type}}),
				    payments = load("payments.csv", {{"order_id", type text}, {"gateway", type text}, {"gross", type number}, {"processing_fee", type number}, {"platform_fee", type number}, {"net_payout", type number}, {"payout_date", type date}}),
				    ar_invoices = load("ar_invoices.csv", {{"invoice_id", type text}, {"order_id", type text}, {"customer_id", type text}, {"invoice_date", type date}, {"terms", type text}, {"due_date", type date}, {"amount", type number}, {"paid_date", type date}})
				  ],
				    raw_products1 = out[raw_products]
				in
				  raw_products1

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

