table search_terms
	lineageTag: 83c0f695-fe01-4b6d-b2ec-b15b92aa7ec5

	measure 'Search Spend' = SUM(search_terms[spend])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: dd321106-df34-4ea0-b7e4-50e213ae3b00

	measure 'Search Revenue' = SUM(search_terms[attributed_revenue])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b0a0d153-949e-4346-9a38-cb24f23fffcf

	measure 'Search ROAS' = DIVIDE([Search Revenue], [Search Spend])
		formatString: 0.00
		lineageTag: 46f8cc82-fdf5-4683-8a64-4686a2a99d42

	measure CPC = DIVIDE([Search Spend], SUM(search_terms[clicks]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 3ca23458-2f5e-416a-9b0e-1d3e725b1dec

	measure 'Wasted Spend' = CALCULATE(SUM(search_terms[spend]), search_terms[orders] = 0)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 65ae8c2b-b8c8-4308-a9c5-96ed6fe4b6ee

	measure '% Wasted Spend' = DIVIDE([Wasted Spend], [Search Spend])
		formatString: 0.0%
		lineageTag: d3cd4a86-15f3-48b3-b3e5-1e4fb978b151

	measure 'Waste Alert Color' = IF(SUM(search_terms[orders]) = 0 && SUM(search_terms[spend]) > 0, "#7F1D1D", BLANK())
		lineageTag: f429b940-d967-4211-89a3-5e966d27818c

	column month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7cb47cb1-2332-4ac9-8a97-fbc5ff1e9b8b
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column channel
		dataType: string
		lineageTag: 7eadd82d-be69-47e4-8fdf-420cdb124bc6
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column campaign
		dataType: string
		lineageTag: 7310d153-13dd-4bcd-b58e-4520612b343f
		summarizeBy: none
		sourceColumn: campaign

		annotation SummarizationSetBy = Automatic

	column search_term
		dataType: string
		lineageTag: 8a55c7e3-9c02-47c1-a1c5-ade0abc96bb5
		summarizeBy: none
		sourceColumn: search_term

		annotation SummarizationSetBy = Automatic

	column impressions
		dataType: int64
		formatString: 0
		lineageTag: 3d1dd908-568a-4d64-ab57-90d49e003e58
		summarizeBy: sum
		sourceColumn: impressions

		annotation SummarizationSetBy = Automatic

	column clicks
		dataType: int64
		formatString: 0
		lineageTag: 2b2869fb-78bd-4e47-8407-e7dd03966566
		summarizeBy: sum
		sourceColumn: clicks

		annotation SummarizationSetBy = Automatic

	column spend
		dataType: double
		lineageTag: 41bc3d06-384c-46cb-8803-cdd76f8c90a4
		summarizeBy: sum
		sourceColumn: spend

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column attributed_revenue
		dataType: double
		lineageTag: 1d4cf6e2-a888-401c-b056-ec84426851cb
		summarizeBy: sum
		sourceColumn: attributed_revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column orders
		dataType: int64
		formatString: 0
		lineageTag: 2617eb6e-fd94-4eec-beeb-34f176edd2c2
		summarizeBy: sum
		sourceColumn: orders

		annotation SummarizationSetBy = Automatic

	partition search_terms = m
		mode: import
		source =
				let
				  dataDir = "C:\Users\camry\OneDrive\Desktop\powerbi-n8n\powerbi\data\",
				  load = (file as text, types as list) =>
				    Table.TransformColumnTypes(
				      Table.PromoteHeaders(
				        Csv.Document(File.Contents(dataDir & file), [Delimiter = ",", Encoding = 65001]),
				        [PromoteAllScalars = true]),
				      types),
				  out = [
				    raw_orders = load("raw_orders.csv", {{"order_id", type text}, {"order_date", type date}, {"channel", type text}, {"customer_id", type text}}),
				    raw_order_lines = load("raw_order_lines.csv", {{"order_id", type text}, {"product_id", type text}, {"qty", Int64.Type}, {"line_total", type number}}),
				    raw_products = load("raw_products.csv", {{"product_id", type text}, {"product_name", type text}, {"brand", type text}, {"unit_cost", type number}, {"unit_price", type number}}),
				    ad_spend = load("ad_spend.csv", {{"spend_date", type date}, {"channel", type text}, {"campaign", type text}, {"spend", type number}, {"attributed_revenue", type number}}),
				    inventory_levels = load("inventory_levels.csv", {{"product_id", type text}, {"location", type text}, {"available", Int64.Type}, {"committed", Int64.Type}, {"incoming", Int64.Type}, {"reorder_point", Int64.Type}}),
				    creators = load("creators.csv", {{"creator_id", type text}, {"handle", type text}, {"name", type text}, {"follower_count", Int64.Type}, {"joined_date", type date}}),
				    creator_attributions = load("creator_attributions.csv", {{"order_id", type text}, {"creator_id", type text}, {"attributed_gmv", type number}, {"commission_rate", type number}, {"commission_usd", type number}, {"refunded", type logical}}),
				    search_terms = load("search_terms.csv", {{"month", type date}, {"channel", type text}, {"campaign", type text}, {"search_term", type text}, {"impressions", Int64.Type}, {"clicks", Int64.Type}, {"spend", type number}, {"attributed_revenue", type number}, {"orders", Int64.Type}}),
				    daily_traffic = load("daily_traffic.csv", {{"date", type date}, {"channel", type text}, {"sessions", Int64.Type}, {"product_views", Int64.Type}, {"add_to_carts", Int64.Type}, {"checkouts", Int64.Type}, {"orders", Int64.Type}}),
				    payments = load("payments.csv", {{"order_id", type text}, {"gateway", type text}, {"gross", type number}, {"processing_fee", type number}, {"platform_fee", type number}, {"net_payout", type number}, {"payout_date", type date}}),
				    ar_invoices = load("ar_invoices.csv", {{"invoice_id", type text}, {"order_id", type text}, {"customer_id", type text}, {"invoice_date", type date}, {"terms", type text}, {"due_date", type date}, {"amount", type number}, {"paid_date", type date}})
				  ],
				    search_terms1 = out[search_terms]
				in
				  search_terms1

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

